site_name: hly1204 的博客

site_description: 个人博客

site_author: hly1204

copyright: Copyright &copy; 2020 - 2021 hly1204

remote_branch: gh-pages # 远程仓库 gh-deploy 会执行的分支

repo_url: https://github.com/hly1204/hly1204.github.io # 仓库 url

repo_name: hly1204/hly1204.github.io # 仓库名

edit_uri: blob/master/docs/

nav:
  - 首页: index.md
  - 文章:
    - 如何构建这个博客: blog/4-9-2021-how_to_build_this_blog.md
    - Montgomery 取模优化算法: blog/12-18-2020-Montgomery_reduction_revisited.md
    - 多点求值和插值: blog/12-23-2020-multipoint_evaluation_and_interpolation.md
    - 下降幂多项式: blog/12-27-2020-falling_factorial_polynomial.md
    - 特征多项式: blog/1-6-2021-characteristic_polynomial.md
    - Lucas 定理: blog/1-12-2021-Lucas_theorem.md
    - 最小树形图: blog/2-16-2021-minimum_directed_spanning_tree.md
    - 快速傅里叶变换: blog/4-10-2021-FFT.md
    - 后缀树: blog/4-12-2021-suffix_tree.md

theme:
  name: material # 主题名，必须，否则为默认
  language: zh
  font:
    text: Noto Serif SC # 思源黑体
    code: Roboto Mono # 默认的代码字体
  direction: ltr # 从左到右
  palette:
    primary: green # 主题颜色
    scheme: default # 亮色主题
    accent: green # 超链接的颜色
  features:
    - navigation.tabs # 有上方的标签
    - toc.integrate # 目录整合在左边
  icon:
    repo: fontawesome/brands/github # 右上角仓库的标志
    admonition:
      note: fontawesome/solid/sticky-note
      abstract: fontawesome/solid/book
      info: fontawesome/solid/info-circle
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/question-circle
      warning: fontawesome/solid/exclamation-triangle
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

extra_javascript:
  - javascripts/load_MathJax.js # 加载 MathJax
  - javascripts/highlight.pack.js # 加载代码高亮，目前代码高亮只有 cpp
  - javascripts/load_highlight.js
  - javascripts/MathJax/es5/tex-chtml.js
  - javascripts/mermaid/dist/mermaid.min.js
  - javascripts/load_mermaid.js

extra_css:
  - stylesheets/github.css # 代码高亮的样式

extra:
  social: # 右下角的
    - icon: fontawesome/brands/github
      link: https://github.com/hly1204
      name: hly1204 on github

markdown_extensions:
  - toc:
    permalink: "&para;"

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight:
      use_pygments: false # 默认为 true 必须关闭，因为这里用的是自己配置的
  - pymdownx.arithmatex:
      smart_dollar: true # 智能识别美元符号，这样就无需在 Markdown 中写多余的转义字符了，代码块会被自动识别出来
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

plugins:
  - git-revision-date-localized:
      type: timeago
